### ISSUE TITLE
Route pattern "/*template" contains a reserved stash value

### ISSUE THREAD

**Issue by eserte** [preaction/Mojolicious-Plugin-Moai#2]
The test suite fails, probably if Mojolicious 9.x is installed:

```

#   Failed test 'No tests run for subtest "Bootstrap4"'
#   at t/lib.t line 13.
Route pattern "/*template" contains a reserved stash value at t/lib.t line 36.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 1.
t/lib.t ................ 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 1/1 subtests 
    # No tests run!
... (etc) ...
```

**Comment by preaction** [comment]
This is fixed by #3. Thanks for reporting this!

**Comment by maksudnurullaev** [comment]
Hi guys!
I need your advice!

My previous version of mojo application works fine with next pattern:
```
$r->any('/:controller/:action/*payload')->via('GET','POST')
  ->to(controller => 'initial', action => 'welcome', payload => undef);
```
But after upgrading now I found the reserved word removed from pattern using. 
Could I easily work around this issue with modern Mojolicious?

**Comment by hussam-qasem** [comment]
> Hi guys! I need your advice!
> 
> My previous version of mojo application works fine with next pattern:
> 
> ```
> $r->any('/:controller/:action/*payload')->via('GET','POST')
>   ->to(controller => 'initial', action => 'welcome', payload => undef);
> ```
> 
> But after upgrading now I found the reserved word removed from pattern using. Could I easily work around this issue with modern Mojolicious?

I believe it doesn't like `:action` or `:status` in the URI. Replace `:action` with something else, e.g. `:myaction`
